### PR TITLE
Add getSelectedRange() API

### PR DESCRIPTION
**Pull request by wglas85**
It took me quite a while to figure out how to retrieve the currently selected range and so I authored this pull request in order to complement the getFocusedCell() API with a getSelectedRange() call.
Moreover, this pull request does change some documentation files fixing some comments and adding a description for getSelectedRange().

### CODE REVIEW

**Comment by revolist** [comment]
@wglas85 merged, sorry for delay.

**Comment by PhSlowSense** [comment]
Thanks, @wglas85 We need this feature !
@revolist When the package will be deployed on npm ? The latest version is 3.0.99 but the latest npm version is 3.0.98.
Thank you

**Comment by alinoil** [comment]
I was just looking for this feature. It has been merged 6 months ago but not yet added to the documentation.

**Comment by ulissepress** [comment]
When this change will be availalble in the  vue3 component?

**Comment by EHadoux** [comment]
Any update on this?

**Pull request merged**
